name: flutter_klarna_inapp_sdk
description: Klarna&#x27;s Flutter wrapper for the In-App SDK
version: 0.0.1
homepage: https://github.com/klarna/flutter-klarna-inapp-sdk

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  test_api: 0.4.8

flutter:
  plugin:
    androidPackage: com.klarna.inapp.sdk.flutter_klarna_inapp_sdk
    pluginClass: FlutterKlarnaInappSdk

